// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeEvent(phrase string, code int) (Event, error) {
	message := Message{
		Content: phrase,
		Code:    code,
	}
	greeter := NewGreeter(message)
	event, err := NewEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}

// wire.go:

var providerSet wire.ProviderSet = wire.NewSet(wire.Struct(new(Message), "Content", "Code"), NewGreeter)
